---
name: CI

on:

  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
    
      - name: Install Ansible
        run: sudo pip install ansible==2.9.22

      - name: Create ansible.cfg with correct roles_path
        run: sudo printf '[defaults]\nhost_key_checking = False\nroles_path=../' > ansible.cfg
  
      - name: Basic role syntax check
        run: sudo ansible-playbook tests/test.yml -i tests/inventory --syntax-check

      - name: Basic role check
        run: sudo ansible-playbook tests/test.yml -i tests/inventory